# Introduction to Numpy

**Numpy** is the reference library of **scipy** for scientific computing. The core of the library consists of **numpy arrays** which allow for easy handling of operations between vectors and matrices. Python arrays are generally **tensors**, which are numerical structures with a variable number of dimensions, and can therefore be one-dimensional arrays, two-dimensional matrices, or multi-dimensional structures (e.g., 10 x 10 x 10 cuboids). To use numpy arrays, we must first import the **numpy** package:

In [130]:
import numpy as np #the "as" notation allows us to reference the numpy namespace simply with np in the future

## Numpy Arrays
A multi-dimensional numpy array can be defined from a list of lists, as follows:

In [131]:
l = [[1,2,3],[4,5,2],[1,8,3]] #a list containing three lists
print("List of lists:",l) #it is displayed as we defined it
a = np.array(l) #I build a numpy array from the list of lists
print("Numpy array:\n",a) #each inner list is identified as a row of a two-dimensional matrix
print("Numpy array from tuple:\n",np.array(((1,2,3),(4,5,6)))) #I can also create numpy arrays from tuples

List of lists: [[1, 2, 3], [4, 5, 2], [1, 8, 3]]
Numpy array:
 [[1 2 3]
 [4 5 2]
 [1 8 3]]
Numpy array from tuple:
 [[1 2 3]
 [4 5 6]]


> **Question 1**
>
> What is an obvious advantage of NumPy arrays compared to lists, given the examples shown above?

Every numpy array has a _shape_ property that allows us to determine the number of dimensions of the structure:

In [132]:
print(a.shape) #it is a 3 x 3 matrix

(3, 3)


Let's look at some other examples:

In [133]:
array = np.array([1,2,3,4])
matrix = np.array([[1,2,3,4],[5,4,2,3],[7,5,3,2],[0,2,3,1]])
tensor = np.array([[[1,2,3,4],['a','b','c','d']],[[5,4,2,3],['a','b','c','d']],[[7,5,3,2],['a','b','c','d']],[[0,2,3,1],['a','b','c','d']]])
print('Array:',array, array.shape) # one-dimensional array, will have only one dimension
print('Matrix:\n',matrix, matrix.shape)
print('matrix:\n',tensor, tensor.shape) # tensor, will have two dimensions

Array: [1 2 3 4] (4,)
Matrix:
 [[1 2 3 4]
 [5 4 2 3]
 [7 5 3 2]
 [0 2 3 1]] (4, 4)
matrix:
 [[['1' '2' '3' '4']
  ['a' 'b' 'c' 'd']]

 [['5' '4' '2' '3']
  ['a' 'b' 'c' 'd']]

 [['7' '5' '3' '2']
  ['a' 'b' 'c' 'd']]

 [['0' '2' '3' '1']
  ['a' 'b' 'c' 'd']]] (4, 2, 4)


> **Question 2**
>
> In Numpy, is there a formal difference between a one-dimensional array and a matrix containing a single row (or a single column)?

Numpy arrays support element-by-element operations. Let's look at the main operations of this type:

In [ ]:
a1 = np.array([1,2,3,4]) 
a2 = np.array([4,3,8,1]) 
print("Sum:",a1+a2) #Vector sum
print("Elementwise multiplication:",a1*a2) #Element-wise multiplication
print("Power of two:",a1**2) #Square of elements
print("Elementwise power:",a1**a2) #Element-wise power
print("Scalar product:",a1.dot(a2)) #Vector scalar product
print("Minimum:",a1.min()) #Array minimum
print("Maximum:",a1.max()) #Array maximum
print("Sum:",a2.sum()) #Sum of all array values
print("Product:",a2.prod()) #Product of all array values
print("Mean:",a1.mean()) #Mean of all array values

Sum: [ 5  5 11  5]
Elementwise multiplication: [ 4  6 24  4]
Power of two: [ 1  4  9 16]
Elementwise power: [   1    8 6561    4]
Vector product: 38
Minimum: 1
Maximum: 4
Sum: 16
Product: 96
Mean: 2.5


Operations on matrices:

In [135]:
m1 = np.array([[1,2,3,4],[5,4,2,3],[7,5,3,2],[0,2,3,1]])
m2 = np.array([[8,2,1,4],[0,4,6,1],[4,4,2,0],[0,1,8,6]])

print("Sum:",m1+m2) #matrix sum
print("Elementwise product:\n",m1*m2) #element-wise product
print("Power of two:\n",m1**2) #square of elements
print("Elementwise power:\n",m1**m2) #element-wise power
print("Matrix multiplication:\n",m1.dot(m2)) #matrix multiplication
print("Minimum:",m1.min()) #minimum
print("Maximum:",m1.max()) #maximum
print("Minimum along columns:",m1.min(0)) #minimum along columns
print("Minimum along rows:",m1.min(1)) #minimum along rows
print("Sum:",m1.sum()) #sum of values
print("Mean:",m1.mean()) #mean value
print("Diagonal:",m1.diagonal()) #main diagonal of the matrix
print("Transposed:\n",m1.T) #transposed matrix

Sum: [[ 9  4  4  8]
 [ 5  8  8  4]
 [11  9  5  2]
 [ 0  3 11  7]]
Elementwise product:
 [[ 8  4  3 16]
 [ 0 16 12  3]
 [28 20  6  0]
 [ 0  2 24  6]]
Power of two:
 [[ 1  4  9 16]
 [25 16  4  9]
 [49 25  9  4]
 [ 0  4  9  1]]
Elementwise power:
 [[   1    4    3  256]
 [   1  256   64    3]
 [2401  625    9    1]
 [   1    2 6561    1]]
Matrix multiplication:
 [[20 26 51 30]
 [48 37 57 42]
 [68 48 59 45]
 [12 21 26  8]]
Minimum: 0
Maximum: 7
Minimum along columns: [0 2 2 1]
Minimum along rows: [1 2 2 0]
Sum: 47
Mean: 2.9375
Diagonal: [1 4 3 1]
Transposed:
 [[1 5 7 0]
 [2 4 5 2]
 [3 2 3 3]
 [4 3 2 1]]


> **Question 3**
>
> What is the advantage of using the operations illustrated above? What code would be needed to perform the operation `a1**a2` if `a1` and `a2` were Python lists rather than numpy arrays?

## Linspace, Arange, Zeros, Ones, Eye and Random

The functions **linspace**, **arange**, **zeros**, **ones**, **eye** and **random** of **numpy** are useful for generating numeric arrays on the fly. In particular, the function **linspace** allows generating a sequence of **n** equally spaced numbers ranging from a minimum value to a maximum value:

In [136]:
a=np.linspace(10,20,5) # generates 5 equally spaced values ranging from 10 to 20
print(a)

[10.  12.5 15.  17.5 20. ]


**arange** is very similar to **range**, but directly returns a **numpy** array:

In [137]:
print(np.arange(10)) #numbers from 0 to 9
print(np.arange(1,6)) #numbers from 1 to 5
print(np.arange(0,7,2)) #even numbers from 0 to 6

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]
[0 2 4 6]


> **Question 4**
>
> Is it possible to obtain the same result as `arange` using `range`? How?

We can create arrays containing zero or one of arbitrary shapes using **zeros** and **ones**:

In [138]:
print(np.zeros((3,4)))#zeros and ones take as a parameter a tuple containing the desired dimensions
print(np.ones((2,1)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1.]
 [1.]]


The function **eye** allows you to create an identity square matrix:

In [139]:
print(np.eye(3))
print(np.eye(5))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


To build an array of random values (uniform distribution) between 0 and 1 (zero included, one excluded), just write:

In [140]:
print(np.random.rand(5)) #an array with 5 random values between 0 and 1
print(np.random.rand(3,2)) #a 3x2 matrix of random values between 0 and 1

[0.4455531  0.15464262 0.73300802 0.83126699 0.4840601 ]
[[0.04519461 0.77306473]
 [0.81167333 0.33469426]
 [0.51806682 0.16306516]]


We can generate an array of random values normally (Gaussian) distributed with **randn**:

In [141]:
print(np.random.randn(5,2))

[[-0.27659656 -1.47446936]
 [ 0.30758864  0.95848991]
 [-0.18955928  0.98689232]
 [-1.06568839  0.79190779]
 [ 0.63691861 -1.36459616]]


We will talk in more detail about the Gaussian distribution later.

We can generate integers between a minimum (inclusive) and a maximum (exclusive) using **randint**:

In [142]:
print(np.random.randint(0,50,3))#three values between 0 and 50 (exclusive)
print(np.random.randint(0,50,(2,3)))#2x3 matrix of random integer values between 0 and 50 (exclusive)

[ 0 26 31]
[[ 7  9  8]
 [47  3 27]]


To generate random values reproducibly, you can specify a seed:

In [143]:
np.random.seed(123)
print(np.random.rand(5))

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]


The code above (including the seed definition) returns the same results if rerun:

In [144]:
np.random.seed(123)
print(np.random.rand(5))

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]


> **Question 5**
>
> What is the effect of re-running the previous cell changing the seed?

## max, min, sum, argmax, argmin

It is possible to calculate maxima and minima and sums of a matrix by rows and columns as follows:

In [145]:
mat = np.array([[1,-5,0],[4,3,6],[5,8,-7],[10,6,-12]])
print(mat)
print()
print( mat.max(0))# Column maximums
print()
print(mat.max(1))# Row maximums
print()
print (mat.min(0))# Column minimums
print()
print(mat.min(1))# Row minimums
print()
print(mat.sum(0))# Column sum
print()
print(mat.sum(1))# Row sum
print()
print(mat.max())# Global maximum
print(mat.min())# Global minimum
print(mat.sum())# Global sum

[[  1  -5   0]
 [  4   3   6]
 [  5   8  -7]
 [ 10   6 -12]]

[10  8  6]

[ 1  6  8 10]

[  1  -5 -12]

[ -5   3  -7 -12]

[ 20  12 -13]

[-4 13  6  4]

10
-12
19


It is also possible to obtain the indices at which there are maxima and minima using the argmax function:

In [146]:
print(mat.argmax(0))

[3 2 1]


We have a maximum in the fourth row in the first column, one in the third row in the second column, and one in the second row in the third column. Let's verify it:

In [147]:
print(mat[3,0])
print(mat[2,1])
print(mat[1,2])
print(mat.max(0))

10
8
6
[10  8  6]


Similarly:

In [148]:
print(mat.argmax(1))
print(mat.argmin(0))
print(mat.argmin(1))

[0 2 1 0]
[0 0 3]
[1 1 2 2]


## Indexing and Slicing
Numpy arrays can be indexed in a similar way to Python lists:

In [149]:
arr = np.array([1,2,3,4,5])
print("arr[0]       ->",arr[0]) #first element of the array
print("arr[:3]      ->",arr[:3]) #first three elements
print("arr[1:5:2]   ->",arr[1:4:2]) #from the second to the fourth (inclusive) with a step of 2

arr[0]       -> 1
arr[:3]      -> [1 2 3]
arr[1:5:2]   -> [2 4]


When indexing an array with more than one dimension using a single index, the first dimension is automatically indexed. Let's look at some examples with two-dimensional matrices:

In [150]:
mat = np.array(([1,5,2,7],[2,7,3,2],[1,5,2,1]))
print("Matrix:\n",mat,mat.shape) #matrix 3 x 4
print("mat[0]     ->",mat[0]) #a matrix is a collection of rows, so mat[0] returns the first row
print("mat[-1]     ->",mat[-1]) #last row
print("mat[::2]     ->",mat[::2]) #odd rows

Matrice:
 [[1 5 2 7]
 [2 7 3 2]
 [1 5 2 1]] (3, 4)
mat[0]     -> [1 5 2 7]
mat[-1]     -> [1 5 2 1]
mat[::2]     -> [[1 5 2 7]
 [1 5 2 1]]


Let's see some examples with multi-dimensional tensors:

In [151]:
tens = np.array(([[1,5,2,7],
                [2,7,3,2],
                [1,5,2,1]],
                [[1,5,2,7],
                [2,7,3,2],
                [1,5,2,1]]))
print("Matrix:\n",tens,tens.shape) #tensor 2x3x4
print("tens[0]    ->",tens[0])#this is the first 3x4 matrix
print("tens[-1]    ->",tens[-1])#last 3x4 matrix

Matrice:
 [[[1 5 2 7]
  [2 7 3 2]
  [1 5 2 1]]

 [[1 5 2 7]
  [2 7 3 2]
  [1 5 2 1]]] (2, 3, 4)
tens[0]    -> [[1 5 2 7]
 [2 7 3 2]
 [1 5 2 1]]
tens[-1]    -> [[1 5 2 7]
 [2 7 3 2]
 [1 5 2 1]]


Indexing can continue through the other dimensions by specifying an additional index in square brackets or by separating the various indices with a comma:

In [152]:
mat = np.array(([1,5,2,7],[2,7,3,2],[1,5,2,1]))
print("Matrix:\n",mat,mat.shape) #matrix 3 x 4
print("mat[2][1]  ->",mat[2][1]) #third row, second column
print("mat[0,0]   ->",mat[0,0]) #first row, first column (more compact notation)

print("mat[0]     -> ",mat[0]) #returns the entire first row of the matrix
print("mat[:,0]   -> ",mat[:,0]) #returns the first column of the matrix.
                                #The two dots ":" mean "leave everything unchanged along this dimension"
print("mat[0,:]   ->",mat[0,:]) #alternative notation to get the first row of the matrix
print("mat[0:2,:] ->\n",mat[0:2,:]) #first two rows
print("mat[:,0:2] ->\n",mat[:,0:2]) #first two columns
print("mat[-1]    ->",mat[-1]) #last row

Matrice:
 [[1 5 2 7]
 [2 7 3 2]
 [1 5 2 1]] (3, 4)
mat[2][1]  -> 5
mat[0,0]   -> 1
mat[0]     ->  [1 5 2 7]
mat[:,0]   ->  [1 2 1]
mat[0,:]   -> [1 5 2 7]
mat[0:2,:] ->
 [[1 5 2 7]
 [2 7 3 2]]
mat[:,0:2] ->
 [[1 5]
 [2 7]
 [1 5]]
mat[-1]    -> [1 5 2 1]


Case of multi-dimensional tensors:

In [153]:
mat=np.array([[[1,2,3,4],['a','b','c','d']],
              [[5,4,2,3],['a','b','c','d']],
              [[7,5,3,2],['a','b','c','d']],
              [[0,2,3,1],['a','b','c','d']]]) 
print("mat[:,:,0] ->", mat[:,:,0]) #matrix contained in the "first channel" of the tensor
print("mat[:,:,1] ->",mat[:,:,1]) #matrix contained in the "second channel" of the tensor
print("mat[...,0] ->", mat[...,0]) #matrix contained in the "first channel" of the tensor (alternative notation)
print("mat[...,1] ->",mat[...,1]) #matrix contained in the "second channel" of the tensor (alternative notation)
#the "..." notation means "leave everything unchanged along the omitted dimensions"

mat[:,:,0] -> [['1' 'a']
 ['5' 'a']
 ['7' 'a']
 ['0' 'a']]
mat[:,:,1] -> [['2' 'b']
 ['4' 'b']
 ['5' 'b']
 ['2' 'b']]
mat[...,0] -> [['1' 'a']
 ['5' 'a']
 ['7' 'a']
 ['0' 'a']]
mat[...,1] -> [['2' 'b']
 ['4' 'b']
 ['5' 'b']
 ['2' 'b']]


Generally, when a subset of data is extracted from an array, it is referred to as **slicing**.

> **Question 6**
>
> Python lists do not support slicing. How can one implement a statement of the type `a[2:8:2]` using Python lists?

## Logical Indexing and Slicing

In numpy it is also possible to index arrays in a "logical" way, meaning by passing an array of boolean values as indices. For example, if we want to select the first and third value of an array, we must pass the array `[True, False, True]` as indices:

In [154]:
x = np.array([1,2,3])
print(x[np.array([True,False,True])]) # To select only 1 and 3
print(x[np.array([False,True,False])]) # To select only 2

[1 3]
[2]


Logical indexing is very useful when combined with the ability to build logical arrays "on the fly" by specifying a condition that array elements may or may not satisfy. For example:

In [155]:
x = np.arange(10)
print(x)
print(x>2) #generates an array of boolean values
#that will contain True for the values of x
#that satisfy the condition x>2
print(x==3) #True only for the value 3

[0 1 2 3 4 5 6 7 8 9]
[False False False  True  True  True  True  True  True  True]
[False False False  True False False False False False False]


By combining these two principles, it is simple to select only some values from an array, based on a condition:

In [156]:
x = np.arange(10)
print(x[x%2==0]) # selects even values
print(x[x%2!=0]) # selects odd values
print(x[x>2]) # selects values greater than 2

[0 2 4 6 8]
[1 3 5 7 9]
[3 4 5 6 7 8 9]


> **Question 7**
>
> Consider the two arrays `a=np.array([1,2,3])` and `b=np.array([5,2,4])`. Use logical indexing to extract the numbers in `a` that are located at positions containing even values in `b`.

## Reshape
In some cases, it can be useful to change the "shape" of a matrix. For example, a 3x2 matrix can be modified by rearranging its elements to obtain a 2x3 matrix, a 1x6 matrix, or a 6x1 matrix. This can be done using the "reshape" method:

In [157]:
mat = np.array([[1,2],[3,4],[5,6]])
print(mat)
print(mat.reshape(2,3))
print(mat.reshape(1,6))
print(mat.reshape(6,1)) #matrix 6 x 1
print(mat.reshape(6)) #one-dimensional vector
print(mat.ravel())#equivalent to the previous one, but parameterless

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


We note that, if we read by rows (from left to right, from top to bottom), the order of the elements remains unchanged. We can also let numpy calculate one of the dimensions by replacing it with -1:

In [158]:
print(mat.reshape(2,-1))
print(mat.reshape(-1,6))

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


Reshape can take as input the individual dimensions or a tuple containing the shape. In the latter case, it is convenient to perform operations of this kind:

In [159]:
mat1 = np.random.rand(3,2)
mat2 = np.random.rand(2,3)
print(mat2.reshape(mat1.shape)) # Give mat2 the same shape as mat1

[[0.72904971 0.43857224]
 [0.0596779  0.39804426]
 [0.73799541 0.18249173]]


## Composing Arrays Using `concatenate` and `stack`
Numpy allows combining different arrays using two main functions: `concatenate` and `stack`. The `concatenate` function takes as input a list (or tuple) of arrays and allows concatenating them along a specified existing dimension (`axis`), which by default is zero (row-wise concatenation):

In [160]:
a=np.arange(9).reshape(3,3)
print(a,a.shape,"\n")
cat=np.concatenate([a,a])
print(cat,cat.shape,"\n")
cat2=np.concatenate([a,a,a])
print(cat2,cat2.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3) 

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]] (6, 3) 

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]] (9, 3)


It is possible to concatenate arrays along a different dimension by specifying it using the `axis` parameter:

In [161]:
a=np.arange(9).reshape(3,3)
print(a,a.shape,"\n")
cat=np.concatenate([a,a], axis=1) #column-wise concatenation
print(cat,cat.shape,"\n")
cat2=np.concatenate([a,a,a], axis=1) #column-wise concatenation
print(cat2,cat2.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3) 

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]] (3, 6) 

[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]
 [6 7 8 6 7 8 6 7 8]] (3, 9)


For the concatenation to be compatible, the arrays in the list must have the same dimensions along those that **are not concatenated**:

In [163]:
print(cat.shape,a.shape) #concatenation along axis 0, dimensions along other axes must be equal

(3, 6) (3, 3)


```python
np.concatenate([cat,a], axis=0) #concatenation by columns #error!
```

The `stack` function, unlike `concatenate`, allows concatenating arrays along a new dimension. Compare the outputs of the two functions:

In [164]:
cat=np.concatenate([a,a])
print(cat,cat.shape)
stack=np.stack([a,a])
print(stack,stack.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]] (6, 3)
[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]] (2, 3, 3)


In the case of `stack`, the arrays were concatenated along a new dimension. It is possible to specify alternative dimensions as in the case of `concatenate`:

In [165]:
stack=np.stack([a,a],axis=1)
print(stack,stack.shape)

[[[0 1 2]
  [0 1 2]]

 [[3 4 5]
  [3 4 5]]

 [[6 7 8]
  [6 7 8]]] (3, 2, 3)


In this case, the arrays have been concatenated along the second dimension.

In [166]:
stack=np.stack([a,a],axis=2)
print(stack,stack.shape)

[[[0 0]
  [1 1]
  [2 2]]

 [[3 3]
  [4 4]
  [5 5]]

 [[6 6]
  [7 7]
  [8 8]]] (3, 3, 2)


In this case, the arrays were concatenated along the last dimension.

## Types
Every numpy array has its type (see https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html for the list of supported types). We can see the type of an array by inspecting the `dtype` property:

In [167]:
print(mat1.dtype)

float64


We can specify the type during array construction:

In [168]:
mat = np.array([[1,2,3],[4,5,6]],int)
print(mat.dtype)

int64


We can also change the type of an array on the fly using `astype`. This is useful, for example, if we want to perform a non-integer division:

In [169]:
print(mat/2)
print(mat.astype(float)/2)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


## Memory Management in Numpy
Numpy manages memory dynamically for efficiency reasons. Therefore, an assignment or a slicing operation generally **does not create a new copy of the data**. Consider for example this code:

In [170]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=a[0,0:2]
print(b)

[[1 2 3]
 [4 5 6]]
[1 2]


The slicing operation `b=a[0,0:2]` only allowed obtaining a new "view" of a part of `a`, but the data was not replicated in memory. Therefore, if we modify an element of b, the modification will actually be applied to `a`:

In [171]:
b[0]=-1
print(b)
print(a)

[-1  2]
[[-1  2  3]
 [ 4  5  6]]


To avoid this kind of behavior, it is possible to use the `copy` method which forces numpy to create a new copy of the data:

In [172]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=a[0,0:2].copy()

print(b)
b[0]=-1
print(b)
print(a)

[[1 2 3]
 [4 5 6]]
[1 2]
[-1  2]
[[1 2 3]
 [4 5 6]]


In this new version of the code, `a` is no longer modified upon modification of `b`.

## Broadcasting
Numpy intelligently handles operations between arrays that have different shapes under certain conditions. Let's look at a practical example: suppose we have a $2\times3$ matrix and a $1\times3$ array:

In [174]:
mat=np.array([[1,2,3],[4,5,6]],dtype=float)
arr=np.array([2,3,8])
print(mat)
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[2 3 8]


Now, suppose we want to divide, element by element, all the values of each row of the matrix by the values of the array. We can perform the required operation using a for loop:

In [175]:
mat2=mat.copy() # Copy the content of the matrix to not overwrite it
for i in range(mat2.shape[0]):# Indexes the rows
    mat2[i]=mat2[i]/arr
print(mat2)

[[0.5        0.66666667 0.375     ]
 [2.         1.66666667 0.75      ]]


In [176]:
arr.shape

(3,)

If we didn't want to use for loops, we could replicate _arr_ to obtain a $2 \times 3$ matrix and then perform a simple element-wise division:

In [177]:
arr2=np.stack([arr,arr])
print(arr2)

print(mat/arr2)

[[2 3 8]
 [2 3 8]]
[[0.5        0.66666667 0.375     ]
 [2.         1.66666667 0.75      ]]


The same result can be obtained simply by asking numpy to divide mat by arr:

In [178]:
print(mat/arr)

[[0.5        0.66666667 0.375     ]
 [2.         1.66666667 0.75      ]]


This happens because **numpy** compares the dimensions of the two operands ($2 \times 3$ and $1 \times 3$) and adapts the operand with the smaller shape to the one with the larger shape, by replicating its elements along the unit dimension (the first one). In practice, broadcasting generalizes operations between scalars and vectors/matrices like:

In [179]:
print(2*mat)
print(2*arr)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[ 4  6 16]


In general, when operations are performed between two arrays, numpy compares the shapes dimension by dimension, from the last to the first. Two dimensions are compatible if:
 * They are equal;
 * One of them is equal to one.

Furthermore, the two shapes do not necessarily have to have the same number of dimensions.
 
For example, the following shapes are compatible:

 $$
 2 \times 3 \times 5 \\
 2 \times 3 \times 5
 $$
 
 $$
 2 \times 3 \times 5 \\
 2 \times 1 \times 5
 $$
 
 $$
 2 \times 3 \times 5 \\
 3 \times 5
 $$
 
 $$
 2 \times 3 \times 5 \\
 3 \times 1
 $$
 
Let's see more examples of broadcasting:

In [180]:
mat1=np.array([[[1,3,5],[7,6,2]],[[6,5,2],[8,9,9]]])
mat2=np.array([[2,1,3],[7,6,2]])
print("Mat1 shape",mat1.shape)
print("Mat2 shape",mat2.shape)
print()
print("Mat1\n",mat1)
print()
print("Mat2\n",mat2)
print()
print("Mat1*Mat2\n",mat1*mat2)

Mat1 shape (2, 2, 3)
Mat2 shape (2, 3)

Mat1
 [[[1 3 5]
  [7 6 2]]

 [[6 5 2]
  [8 9 9]]]

Mat2
 [[2 1 3]
 [7 6 2]]

Mat1*Mat2
 [[[ 2  3 15]
  [49 36  4]]

 [[12  5  6]
  [56 54 18]]]


The product between the two tensors was performed by multiplying the two-dimensional matrices `mat1[0,...]` and `mat2[0,...]` by `mat2`. This is equivalent to repeating the elements of `mat2` along the missing dimension and performing a point-by-point product between `mat1` and the adapted version of `mat2`.

In [181]:
mat1=np.array([[[1,3,5],[7,6,2]],[[6,5,2],[8,9,9]]])
mat2=np.array([[[1,3,5]],[[6,5,2]]])
print("Mat1 shape",mat1.shape)
print("Mat2 shape",mat2.shape)
print()
print("Mat1\n",mat1)
print()
print("Mat2\n",mat2)
print()
print("Mat1*Mat2\n",mat1*mat2)

Mat1 shape (2, 2, 3)
Mat2 shape (2, 1, 3)

Mat1
 [[[1 3 5]
  [7 6 2]]

 [[6 5 2]
  [8 9 9]]]

Mat2
 [[[1 3 5]]

 [[6 5 2]]]

Mat1*Mat2
 [[[ 1  9 25]
  [ 7 18 10]]

 [[36 25  4]
  [48 45 18]]]


In this case, the product between the two tensors was obtained by multiplying all rows of the two-dimensional matrices `mat1[0,...]` by `mat2[0]` (first row of mat2) and all rows of the two-dimensional matrices `mat1[1,...]` by `mat2[1]` (second row of mat2). This is equivalent to repeating all elements of `mat2` along the second dimension (the one containing $1$) and performing an element-wise product between `mat1` and the adapted version of `mat2`.

## Exercises

> **Exercise 1**
>
> Define a 3x4 matrix, then:
> * Print the first row of the matrix;
> * Print the second column of the matrix;
> * Sum the first and last columns of the matrix;
> * Sum the elements along the main diagonal;
> * Print the number of elements in the matrix.

> **Exercise 2**
>
> Generate an array of $100$ numbers between $2$ and $4$ and calculate the sum of the elements whose squares have a value greater than $8$.

> **Exercise 3**
>
> Generate the following matrix writing the smallest amount of code possible:
>
> ```
> 0 1 2
> 3 4 5
> 6 7 8
> ```
>
> Repeat the exercise generating a $25 \times 13$ matrix of the same type.